### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by juliolitwin** [Cr33zz/Nav#2]
Hey,

It's amazing to be able to find such a project open src. ;)

I have some doubts:

- What status is the project currently in? ready-for-production?
- In terms of performance, how do you compare to the others? Is there a huge use of GC?
- Is Nav used in any projects?
- Implementation for Unity, would it be something out of the box? 

Cheers.

**Comment by Cr33zz** [comment]
Hey, thanks :) 

This is a hobby project and as such, I wouldn't use that in a professional solution and expect it to work out of the box (it needs some parameters tuning based on your metrics). I'm personally using it in one of my projects and it works perfectly fine. 

Performance is of course relative based on your time constraints. It is decently optimized at least for my needs (single-agent navigation) :D, pathfinding is quite fast (we are talking a couple of milliseconds for long paths usually), and I did some extra optimizations for super long paths and smoothing. I didn't measure GC usage, but I was heavily profiling the library and was focused on CPU performance.

You can use it in any C# based project. Unfortunately, I don't know the exact requirements for Unity, and never tried to integrate it with that engine.

Hope that shed some light on the situation.
